### ISSUE TITLE
Is it possible to use this plugin with Windows Azure Pack (private cloud)?

### ISSUE THREAD

**Issue by nkot** [JetBrains/teamcity-azure-agent#10]
Just wondering if it is possible to use the plugin with Windows Azure Pack (private cloud)?

**Comment by mkuzmin** [comment]
We didn't test it yet. Please try, and we will happy to help you, if you meet any issues.

**Comment by dimyriy** [comment]
@nkot Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61954 for updates.
