### ISSUE TITLE
Core Quota Limit in Azure is not handled gracefully

### ISSUE THREAD

**Issue by tfabris** [JetBrains/teamcity-azure-agent#100]
## Description

When the Team City Cloud Agent plugin tries to spin up a new agent machine, but Azure responds with an error message because it would exceed the quota limits for Machine Cores in the Azure Subscription, a problem occurs.

Expected:
- Plugin attempts to create a new Agent and receives this error message from Azure: "Operation results in exceeding quota limits of Core. Maximum allowed: 500, Current in use: 498, Additional requested: 4. Please read more about quota increase at http://aka.ms/corequotaincrease. (OperationNotAllowed) (Conflict)"
- Plugin should gracefully halt the process of attempting to create this new machine, and the machine should not be created.
- Plugin should deliver a clear, actionable error message to the Team City user interface, in the "Agents" screen in the "Clouds" tab.

Actual:
- Plugin attempts to create a new Agent and receives this error message from Azure: "Operation results in exceeding quota limits of Core. Maximum allowed: 500, Current in use: 498, Additional requested: 4. Please read more about quota increase at http://aka.ms/corequotaincrease. (OperationNotAllowed) (Conflict)"
- No error message is shown in Team City.
- Plugin continues to try to create the new machine, and it is created, but only partially.
- Strange things happen. The entire deployment template is not applied, and so the resulting virtual machine is only partially functional.
- Virtual machine still connects to Team City and shows up in the "Agents/Connected" tab, but the machine is not able to correctly complete the running of any builds or tests.
- Agent machines are not registering in DNS properly with their correct DNS names. For instance if I want to connect to the remote desktop of one of these machines, I have to connect to it via IP address instead of via machine name.
- The machines are losing connectivity with Team City frequently, canceling builds, and shutting down or rebooting unexpectedly at times.
- On the virtual machines, when you view the System Properties dialog box (i.e., you run SYSDM.CPL) and look at the settings, it shows the wrong name in the machine name screen (this is the root cause of the DNS problem cited above). I believe this might be occurring because the full deployment template was not applied by the plugin.
- The machines show their old image/template source name from when they were created. For example, if the machine image template was created from a computer named “hybrid42-13”, then that is what is shown in the System Properties screen, instead of the machine's assigned new/expected name such as "hybrid43-1"

## Environment

* TeamCity version: TeamCity Enterprise 2018.1.1 (build 58406)
* Azure plugin version: 0.8.5

## Diagnostic logs

The file "teamcity-clouds.log" contains multiple messages like shown below, these messages are the source of the problem. These are the instances which should be gracefully handled.

```
[2018-08-10 11:37:50,724]   WARN [onPool-worker-2] - ouds.azure.arm.AzureCloudImage - Failed to create deployment hybrid44-18 in resource group HybridAgentsGen44: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. Operation results in exceeding quota limits of Core. Maximum allowed: 500, Current in use: 498, Additional requested: 4. Please read more about quota increase at http://aka.ms/corequotaincrease. (OperationNotAllowed) (Conflict): jetbrains.buildServer.clouds.CloudException: Failed to create deployment hybrid44-18 in resource group HybridAgentsGen44: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. Operation results in exceeding quota limits of Core. Maximum allowed: 500, Current in use: 498, Additional requested: 4. Please read more about quota increase at http://aka.ms/corequotaincrease. (OperationNotAllowed) (Conflict) (enable debug to see stacktrace)
```

Attached is a teamcity-clouds.log file showing the problem occurring. Things are fine for a few days in the log, and then a problem occurs when I am trying to spin up a new generation of Agent machines based on a new image/template. The problem starts occurring at [2018-08-10 11:37:50,724] where the first instance of the Core Quota error starts occurring. then multiple instances repeat after that.

[teamcity-clouds.log](https://github.com/JetBrains/teamcity-azure-agent/files/2284094/teamcity-clouds.log)

**Comment by dtretyakov** [comment]
@tfabris, in the latest plugin version was added handling of Azure CPU Quota errors which prevents starting new cloud instances for the image until some active instances has gone.
