### ISSUE TITLE
Containers - support providing manifest file

### ISSUE THREAD

**Issue by omerlh** [JetBrains/teamcity-azure-agent#114]
## Description

Azure Container Instance support configuring a container via a manifest file (see an example [here](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-yaml)), which let you configure some advanced scenarios like networking on managed identity. Those features can be enabled via the UI, but supporting manifest files is better - new features will be supported out of the box, without additional changes to the plugin.

**Comment by dtretyakov** [comment]
@omerlh, right now you could use [a custom Resource Manager template](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-multi-container-group) to create ACI containers. You could take a look at the [template image type](https://github.com/JetBrains/teamcity-azure-agent/wiki/Template-Image) and please let us know if you're missing something in it.

**Comment by omerlh** [comment]
It's a good workaround - but not exactly what I want: I want different builds to run different images, based on the repository. This is relevant when using Azure MSI - different builds need different permissions etc.

**Comment by dimyriy** [comment]
@omerlh Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61942 for updates.
