### ISSUE TITLE
The resource manager create the containers instances but doesn't allocate IP to the container

### ISSUE THREAD

**Issue by moattarwork** [JetBrains/teamcity-azure-agent#115]
## Description

Setting up the azure resource manager to create agents, create all of the required infrastructure but as it's in private network in azure, It doesn't allocate IP address properly to the instances of the agent. This is causing issue with the instance to connect to team city server and register itself as agent.

Due to the documentation and if I try to create the container instances manually in Azure I have the choice of using Public IP or Private VNet + Subnet which is not available in team city plugin.

## Environment

* TeamCity version: 2019.1
* Azure plugin version: 0.8.11

**Comment by dimyriy** [comment]
@moattarwork Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61941 for updates.
