### ISSUE TITLE
Default vmNamePrefix doesn't pass validation (too long)

### ISSUE THREAD

**Issue by ajaskier** [JetBrains/teamcity-azure-agent#117]
## Description
When adding agent image, the default value of `Name Prefix` field is `teamcity-agent`. That value doesn't pass the validation of that field. Information about failed validation is not displayed unless the field gets modified.

I'm attaching screenshots with dialog window:

(initial state)
![shutter_tc_before](https://user-images.githubusercontent.com/8076184/66474570-db2fa100-ea91-11e9-96e1-568e632bda4c.png)

(after modifying the field)
![shutter_tc_after](https://user-images.githubusercontent.com/8076184/66474594-eda9da80-ea91-11e9-90a1-584cc658da10.png)

## Environment

* TeamCity version: 2019.1 (build 65998)
* Azure plugin version: 0.9.1

**Comment by dimyriy** [comment]
@ajaskier, Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-62666 for updates.
