### ISSUE TITLE
Cannot add Azure image - Save button is disabled

### ISSUE THREAD

**Issue by arackcheev** [JetBrains/teamcity-azure-agent#119]
## Description

We cannot add an image we prepared. Save button is constantly disabled and it's not clear why

![save button](https://user-images.githubusercontent.com/5525999/71265822-20a50000-2358-11ea-88ce-2836ae24a437.png)

## Environment

* TeamCity version: 2019.2 (build 71499)
* Azure plugin version: 0.9.1

## Diagnostic logs

There is nothing relevant in teamcity-clouds.log

**Comment by arackcheev** [comment]
Just figured it out. We had to change Agent name field. It doesn't show any warning, but as soon as we edit it Save button becomes enabled. Another issue is that if I would enter "teamcity-agent" as a name manually there is a warning that this field could not be longer than 12 chars

**Comment by AChubatova** [comment]
The issue in JetBrains YouTrack https://youtrack.jetbrains.com/issue/TW-62666
