### ISSUE TITLE
Plugin does not see started instances on existing VM

### ISSUE THREAD

**Issue by wooferclaw** [JetBrains/teamcity-azure-agent#121]
## Description

I create cloud profile and add existing VM as cloud instance. 
In this case it cannot connect cloud build agent with this already running instance. 
As a result it thinks that buildagent is idle, while defacto it is running builds, so it stops the VM during running build.

## Environment

* TeamCity version: 2019.2.4 build 72059 (latest)
* Azure plugin version: snapshot from 12.03.2020

## Diagnostic logs

![idle_VM](https://user-images.githubusercontent.com/8898952/81689998-74c59380-9463-11ea-809b-e0e81df4fc1a.jpg)

**Comment by IlyaFomenko** [comment]
Azure plugin matches existing VM via azure.instance.name property. 
Please specify it as described [here](https://github.com/JetBrains/teamcity-azure-agent#teamcity-starts-virtual-machine-instance-but-agent-is-unauthorized)

**Comment by wooferclaw** [comment]
Thanks for the quick response, that helped. 
Now everything works as expected.
