### ISSUE TITLE
Should be able to set max instances for an entire cloud profile, rather than per-image

### ISSUE THREAD

**Issue by dlwyatt** [JetBrains/teamcity-azure-agent#15]
This would provide parity with the EC2 plugin, where we can use any number of AMIs, but set the max instances (in any combination) for the profile.

**Comment by dlwyatt** [comment]
It's probably very ugly (since I'm a virtual newbie to JavaScript), but I've got this working in my fork over at https://github.com/dlwyatt/teamcity-azure-plugin/tree/ProfileLevelMaxInstances .  I'll be using this fork of the plugin for our build server, and if you'd like, I can send the code back this way via a pull request.

**Comment by paksv** [comment]
We are actually considering having this option in the cloud core. Probably in the scope of Teamcity 10.0

**Comment by dimyriy** [comment]
@dlwyatt Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61953 for updates.
