### ISSUE TITLE
TeamCity server causing “TooManyRequests” when interacting with Azure RDFE API

### ISSUE THREAD

**Issue by danielstocker** [JetBrains/teamcity-azure-agent#43]
Dear TeamCity team, 
[azure-cloud-log.txt](https://github.com/JetBrains/teamcity-azure-plugin/files/479760/azure-cloud-log.txt)

I am a support engineer in the Azure IaaS platform team and am investigating the following issue with a customer of ours. 

**Infrastructure setup**

The customer is running a TeamCity server with the Azure plugin on an Azure Windows machine. Since last week they have been seeing errors in the server logs. All of them are exceptions thrown due to the API responding with a “Too Many Requests” error code. 

All errors are reported from operations interacting with Classic (ASM) resources. 

**Subscription Layout**

_Classic Resources_

• IaaS
o   1 cloud service with 3 Windows machines 
 one of these is the TeamCity server
o   3 cloud services with one Windows machine each
o   2 cloud services with 3 Linux machines each
o   3 cloud services with one Linux machine each
• PaaS
o   1 cloud service (Small)

 _ARM Resources_

• 1 development resource group with 8 Linux machines
• 1 integration/staging resource group with 4 Linux machines
• 1 production resource group with 6 Linux machines
• 1 monitoring resource group with one machine
• 1 statistics resource group with one machine
Infrastructure Locations
• North Europe 
• West Europe

**Error Logs**

Error logs can be found in the attached file.

**Investigations on the Azure side**

What we see on the API side is the server issuing lots of “GetDeployment” requests. Some of them end in a 404, but most of the ones that respond have the standard “Production, Staging” – which is common for IaaS cloud services. 

The behaviour shown on the API level seems to indicate that the JetBrains cloud client https://github.com/JetBrains/teamcity-vmware-plugin/blob/db16c3abb729225ec09f8486e70beea9d4f7038d/cloud-vmware-server/src/main/java/jetbrains/buildServer/clouds/base/AbstractCloudClient.java issues continuous requests to check name availabilities and get all deployments of each cloud service whenever a response comes back partly incomplete.

This seems to continue until all “GetDeployment” requests or all “CheckNameAvailability” requests return an error “TooManyRequests” which then leads to the exception being logged. 
In some 20 minute periods we see +3000 requests from the build server, most of them “GetDeployment”. (details on GetDeployment: https://msdn.microsoft.com/en-us/library/azure/ee460804.aspx) 

More context on the concept of throttling at an API level

If more than 150 requests are issued in a 5-minute period to the Azure Classic API, Azure will classify the origin IP of the requests a “high requestor”. If the number of request increases the API will apply throttling over time. 

Our review has shown that the behaviour described had occurred since the beginning of September, but the throttling had intensified early last week (12th of September onwards).
To ensure that retries of a request do not get throttled, we recommend to delay retries, increasing the delay with each retry to avoid a scenario where large numbers of requests (retries and fresh requests) hit the API at the same time. (We can observe this in the customer’s subscription. The origin of the requests is the machine running team city) 

**Microsoft Contacts**

dasto@microsoft.com – until the 19th of September
emilianb@microsoft.com – 20th of September onwards

**Additional data** 

Please do not hesitate to contact us if you require additional information. I will pass the link to this bug on to our customer as well so that you can communicate directly.

**Comment by danielstocker** [comment]
Attached file https://github.com/JetBrains/teamcity-azure-plugin/files/479760/azure-cloud-log.txt

**Comment by dimyriy** [comment]
@danielstocker Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61952 for updates.
