### ISSUE TITLE
Template deployment parameters

### ISSUE THREAD

**Issue by catalystjs** [JetBrains/teamcity-azure-agent#63]
I know this is a new feature in the code, but I was hoping to get a better sense of how to supply the params  when using the template option for provisioning versus an image. Is there any limited documentation available on how to get this done?

**Comment by dtretyakov** [comment]
@catalystjs, currently template deployment mode does not support parameters, so you could use variables section in ARM template for that. When TeamCity will support [project parameters for cloud profiles](https://youtrack.jetbrains.com/issue/TW-51157) we could be able to use them in template field.

Currently you could set default template value by clicking on the icon on the right of template field, where you need to replace `...` by resource identifiers.

If your concern about UI and you want to see dedicated parameters section please let me know.

**Comment by dimyriy** [comment]
@catalystjs Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61951 for updates.
