### ISSUE TITLE
long queue targeting a particular agent is causing the plugin to spawn more agents

### ISSUE THREAD

**Issue by btdevopsteam** [JetBrains/teamcity-azure-agent#65]
Good day

We notice this behavior
- queue multiple builds targeting a **particular agent**, e.g. queue 10 builds for agent-1
- the plugin would attempt to spin up 10 agents (or as many as the limit set)
- only agent-1 is building, agent-2, 3, 4, etc would be idling
- after the set idling time, e.g. 30 minutes, the plugin would stop agent-2, 3, 4, etc
- the queue length drops to for e.g. 8 for agent-1
- the plugin will attempt to spin up agents again
- etc, etc

**Comment by dimyriy** [comment]
@btdevopsteam Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61950 for updates.
