### ISSUE TITLE
Add integration with Templates on Azure Portal

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-azure-agent#87]
Currently Azure Portal in preview mode allows to store templates:
![image](https://user-images.githubusercontent.com/1025927/35743707-a73a3f7c-083e-11e8-90cb-0393acd7bdfb.png)

**Comment by dimyriy** [comment]
@dtretyakov Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61947 for updates.
