### ISSUE TITLE
Agent name is cropped for start/stop instances

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-azure-agent#89]
@gambrose:
> I did notice an issue with the Name Prefix missing the first letter of the image name.
https://github.com/JetBrains/teamcity-azure-plugin/issues/37#issuecomment-367124946

**Comment by gambrose** [comment]
I just tested SNAPSHOT-20180314170906 to see if this issue was fixed for me.

After removing my misnamed VM I found now I cannot add any existing VMs as the save button is always disabled.
![image](https://user-images.githubusercontent.com/2676070/37465481-21ac53f6-2853-11e8-86e5-ce104dde6977.png)

**Comment by dtretyakov** [comment]
@gambrose, thanks for reporting this problem. Validation rules were fixed in the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1&tab=buildTypeStatusDiv).

Please let me know if it helps.

**Comment by gambrose** [comment]
Tested SNAPSHOT-20180315170817

The save button is still disabled for the majority of VMs. I did notice that a couple of VMs could be saved I'm not sure if that has changed since the last tested version or not.

**Comment by dtretyakov** [comment]
@gambrose, thanks for verification, finally fixed validation rules for start/stop mode in the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1&tab=buildTypeStatusDiv).

**Comment by gambrose** [comment]
Tested SNAPSHOT-20180316100346 and can confirm it is now working.
