### ISSUE TITLE
Automatic authorization of VM instances in Start/Stop mode

### ISSUE THREAD

**Issue by gambrose** [JetBrains/teamcity-azure-agent#92]
## Description

I have added a ARM cloud agent using an existing VM image. But then the agent starts up and connects TeamCity does not link the new agent to the cloud instance.

![image](https://user-images.githubusercontent.com/2676070/37531716-d67cdf8a-2934-11e8-8bc9-3084458da8a3.png)

Alec is name of agent on server TeamcityAgent-006
James is name of agent on server TeamcityAgent-007

![image](https://user-images.githubusercontent.com/2676070/37532092-f5371192-2935-11e8-88e0-ed3ab831ce6a.png)

I have had these agents connected to TeamCity before I setup the cloud integration but I have deleted the agents before adding the cloud agents. 

## Environment

* TeamCity version: 10.0.5 (build 42677)
* Azure plugin version: snapshot-20161703150130

**Comment by dtretyakov** [comment]
@gambrose, could you please inspect whether these virtual machines were actually connected to the TeamCity server? You could see it on the Agents -> Unauthorized or Disabled tabs.

Also it would be great to take a look at the `teamcity-agent.log` and `teamcity-clouds.log` files. Could you please file an issue in TeamCity tracker and securely attach the mentioned files?
https://github.com/JetBrains/teamcity-azure-agent#problems-investigation

**Comment by gambrose** [comment]
The machines connect and are visible in the Unauthorized tab. I have since authorised them and they are connected and working just not associated with the cloud profile.

I think I have attached the files in a secure manner. https://youtrack.jetbrains.com/issue/TW-54213

**Comment by dtretyakov** [comment]
@gambrose, thanks for details. Will try to find a proper fix for that.

As a workaround, please authorize these build agents manually.

**Comment by gambrose** [comment]
Thanks @dtretyakov.
The authorisation isn't really the issue. It's more that the machines will be stopped after the inactivity timeout (30 mins) and will not be restarted. I think they are stopped even if they are in the middle of building.

**Comment by dtretyakov** [comment]
@gambrose, ok, in this case workaround is following:

On each virtual machine please append the following line in the [buildagent.properties file](https://confluence.jetbrains.com/display/TCDL/Build+Agent+Configuration):
```
azure.instance.name=...
```

Then after build agent service restart authorization and problem with inactivity timeout should be solved.

**Comment by gambrose** [comment]
Thanks @dtretyakov

I noticed that the classic azure cloud server is now not being authorised automatically.
I am just upgrading our version TeamCity server as we are on quite an old version 10.0.5 (build 42677). I will try that workaround when I have everything upgraded.

**Comment by gambrose** [comment]
Setting the `azure.instance.name` in the buildagent.properties file worked as a workaround. The agents are correctly associated with their cloud instances.

**Comment by NCL-liamkelly** [comment]
I'm experiencing the same problem. Is there any other work arounds / fixes other than what's mentioned above yet?

**Comment by beaudryj** [comment]
Also in the same boat as @NCL-liamkelly

**Comment by NCL-liamkelly** [comment]
@beaudryj how are you deploying your agents? We're using puppet so the fix mentioned above is no longer a big deal, we've just added the correct line to the config.

We're considering making the puppet module we've created for TeamCity public at some point too.

**Comment by beaudryj** [comment]
I’m still trying to figure that out, my image needs Docker For windows
installed and sysprep wipes it out, so possibly just going to do an arm
template with a .ps1 and chocolatey

**Comment by dimyriy** [comment]
@gambrose Issue has been moved to JetBrains YouTrack. Please, follow the issue https://youtrack.jetbrains.com/issue/TW-61946 for updates.
