### ISSUE TITLE
Don't continually start and stop VMs if no communication is possible

### ISSUE THREAD

**Issue by tom-dudley** [JetBrains/teamcity-azure-agent#99]
I have recently encountered an issue where our agents were unable to communicate with the server even though the server could query the Azure API. The consequence of this is that (with some queued builds) the plugin decides to start some agents which then sit idle for some time (since they can't communicate with the server) and then get turned off. This cycle repeats indefinitely until the network issue which affects client/server communication is fixed.

Since the server knows when the agent is started and stopped, as well as knowing that it couldn't communicate with the agent at all during that period, I think the server should reduce attempts to start the agent via either:
* Completely stopping after 3 successive failed attempts, and try again in 24 hours
* Perform an exponential back-off which gets reset after successful communication

**Comment by dtretyakov** [comment]
@tom-dudley, thanks for reporting this use case. I've moved it into feature request for TeamCity cloud core since it could be useful for all cloud integrations: https://youtrack.jetbrains.com/issue/TW-55993
